#!/usr/bin/env bash

#:: Adeptio dev team
#:: Copyright // 2019-01-08
#:: Version: v2.0.0.0

set -e
Intall_log='/var/log/syslog'

# Check if we have adeptiocore.service?
sudo systemctl daemon-reload
file="/etc/systemd/system/adeptiocore.service"
if [ -e "$file" ]; then 
    sudo systemctl stop adeptiocore
else
    echo "" &> /dev/null
fi
